stages:
  - build
  - style_guide
  - pages

#clang_tests:
#  image: gitlab.labsec.ufsc.br:666/sgc/tools/docker/rhel74:clang-format
#  stage: style_guide
#  tags:
#    - docker
#  script:
#    - find . -name "*.cpp" ! -name GlobalMessages.cpp ! -name ManagerialReport.cpp ! -name YwapaEnum.cpp ! -name UiTestController.cpp ! -name LogDescriptor.cpp | xargs clang-format -n -Werror
#  allow_failure: true

.lib_vars: &lib_vars
  - export OPENSSL_PREFIX=/usr/local/ssl
  - export OPENSSL_LIBDIR=$OPENSSL_PREFIX/lib 
  - export LIBP11_PREFIX=/usr/local 
  - export LIBP11_LIBDIR=$LIBP11_PREFIX/lib 
  - export LIBP11_INCLUDEDIR=$LIBP11_PREFIX/include 
  - export INSTALL_PREFIX=/usr 
  - export INSTALL_LIBDIR=$INSTALL_PREFIX/lib64 

libcryptosec_build:
  image: gitlab.labsec.ufsc.br:666/sgc/tools/docker/rhel74:libcryptosec_gtest
  stage: build
  before_script:
    *lib_vars
  script:
    - make -j12

libcryptosec_gtest:
  image: gitlab.labsec.ufsc.br:666/sgc/tools/docker/rhel74:libcryptosec_gtest
  stage: build
  before_script:
    *lib_vars
  script:
    - make
    - make install
    - cd tests/
    - make -j12
    - ./test.out

libcryptosec_rpmbuild:
  image: gitlab.labsec.ufsc.br:666/sgc/tools/docker/rhel74:rpmbuild
  stage: build
  script:
    - cp libcryptosec.spec /root/rpmbuild/SPECS/libcryptosec.spec
    - export VERSION=$(grep 'libcryptosec.spec' -e "Version:" | awk -F ' ' '$0=$2')
    - export RELEASE=$(grep 'libcryptosec.spec' -e "Release:" | awk -F ' ' '$0=$2')
    - export YWP_VERSION=libcryptosec-$VERSION
    - export RPM_VERSION=$YWP_VERSION-$RELEASE
    - export PROJ_PATH=$(basename "$PWD")
    - cd ..
    - cp -r $PROJ_PATH $YWP_VERSION
    - tar -zcf $YWP_VERSION.tar.gz $YWP_VERSION
    - mv $YWP_VERSION.tar.gz /root/rpmbuild/SOURCES/
    - cd /root
    - rpmbuild -ba rpmbuild/SPECS/libcryptosec.spec
    - lftp -e "cd transfer/yyy/; put /root/rpmbuild/RPMS/x86_64/$RPM_VERSION.x86_64.rpm; bye" -u yyy,"Ywapyra&1418" artifacts.labsec.ufsc.br
  only:
    - tags 
          
pages:
  image: alpine
  stage: pages
  script:  
  - apk update
  - apk add doxygen
  - doxygen Doxyfile
  - mv codedoc/html/ public/
  artifacts:
    paths:
    - public
  only:
    - tags
